### ISSUE TITLE
Add the remaining test suites to lagoon-test

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-charts#118]
Currently we only run `features-kubernetes` in the `lagoon-test` test suite.

We should also run:
* `nginx`
* `drupal`
* `active-standby-kubernetes`

**Comment by tobybellwood** [comment]
I've tested the `drupal` version with my branch at https://github.com/amazeeio/lagoon/compare/lagoon-core-tests (changing the api/ssh data in lagoon.yml and setting the correct drush alias) - and making the change to add the bulk storage class to the cluster to allow RWX (details in https://gist.github.com/tobybellwood/edf20e7d5a8eb0d0e7a89e708817d308)
