### ISSUE TITLE
Remove update-push-images.sh from lagoon-remote chart

### ISSUE THREAD

**Issue by xantrix** [uselagoon/lagoon-charts#151]
In k8s we do not need anymore to push to the Openshift registry
https://github.com/amazeeio/lagoon/blob/main/images/docker-host/update-push-images.sh
so we can remove it from Deployment chart https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-remote/templates/docker-host.deployment.yaml#L46

This will solve the following issue in the k8s clusters.

```bash
go-crond: failed cronjob: cmd:/lagoon/cronjob.sh "/update-push-images.sh" out:2020-11-10T15:15:00Z CRONJOB: /update-push-images.sh
++ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
+ NAMESPACE=lagoon
+ docker -H localhost info
+ docker login -u=serviceaccount --password-stdin registry.lagoon.svc:5000
Error response from daemon: Get http://registry.lagoon.svc:5000/v2/: dial tcp: lookup registry.lagoon.svc on 172.20.0.10:53: no such host
 err:exit status 1 time:166.646926m
```

**Comment by smlx** [comment]
thanks for finding this!

I'm not 100% sure what the purpose of this script is. If you can confirm that it's not needed on k8s did you want to create a PR?

**Comment by xantrix** [comment]
hi @smlx 
I'm going to have a deeper look into it and of course happy to make a PR :)
