### ISSUE TITLE
Switch to upstream ssh-portal image once PR merged

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-charts#163]
https://github.com/amazeeio/lagoon/pull/2179

**Comment by tobybellwood** [comment]
we should probs just merge the PR in - given it's non-destructive?

**Comment by smlx** [comment]
Ah, it's still dependent on some changes in the API before it's usable.

**Comment by smlx** [comment]
Superseded by https://github.com/uselagoon/lagoon-charts/pull/382
