### ISSUE TITLE
discussion about lagoon-remote charts

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-charts#175]
currently we have now these pieces inside the lagoon-remote chart:
- dbaas-operator
- dioscuri
- lagoon-build-deploy

each of them have their own charts existing and there is a possibility to maybe want to install these pieces individually without lagoon-remote (like dbaas-operator can be used on non-lagoon clusters), for lagoon-build-deploy we would like to install this on old openshift clusters (see AMAZEEIO-3440)

Therefore we expected that the lagoon-remote would just use subcharts for these tools instead of actually having the templates for it part of lagoon-remote chart.

**Comment by smlx** [comment]
Thanks for opening the discussion. It's something I've been thinking about too.

I rolled those services into `lagoon-remote` for a few reasons:

1. Expediency getting to Lagoon 2.0, knowing we can always split them out to subcharts later.
2. Some of those services are very tightly coupled to Lagoon. For example `lagoon-build-deploy` doesn't make much sense outside of Lagoon. And active-standby doesn't work if `dioscuri` isn't there. I liken these to e.g. the webhook services - you can deploy Lagoon without them but features are missing and why would you want them installed without the rest of Lagoon?
3. It wasn't clear if there was a helm repo for those charts or what the plan was for them going forward.

So to figure out what to do here I think we need to answer a few questions:

1. For each of the services you mentioned, does it make sense to have a standalone chart (e.g. is there a use-case for deployment outside of `lagoon-remote`)?

* `dioscuri`
* `lagoon-build-deploy`
* `dbaas-operator`

2. In the case that a standalone chart makes sense, which git repo should this chart live in?

* Stay in each project git repo (the way it is now)?
* Move to this git repo?
* Create a new git repo to hold charts for services used by lagoon, but not strictly part of lagoon? (e.g. `amazeeio/charts`?)

3. In the case that a standalone chart makes sense, which helm repo should this chart live in?

* Just use `https://raw.githubusercontent.com/...`?
* This one `https://uselagoon.github.io/lagoon-charts/`?
* A new repo like `https://amazeeio.github.io/charts/` or even `https://charts.amazee.io/`?

My own opinions (not strongly held though, happy to have my mind changed!):

1. Standalone chart definitely makes sense for `dbaas-operator`, maybe for `dioscuri`, but not for `lagoon-build-deploy`.
2. There is enough of a difference between _development_ of the service and _deployment_ of the service that a separate git repo holding charts services used by Lagoon but possible to use outside of Lagoon makes sense. That way we can also decouple maintenance/release of the _service_ and of the _chart_.
3. Following on from 2, there should be a central charts repo like `https://amazeeio.github.io/charts/`.

As the upstream author of these services, it would be good to get @shreddedbacon's opinion here too.

**Comment by shreddedbacon** [comment]
The only one I see as being separate is `dbaas-operator` as this is not specific to lagoon in anyway, anyone could take this and install it and use it however they want. `dbaas-operator` is an amazeeio project, so if anything it should be in a seperate amazeeio-charts repo.

To an extent `dioscuri` is the same, while its primary use is for active/standby, anyone could use it themselves for something, so it would be better to sit with the `dbaas-operator`

I think it makes sense to
* Move the `lagoon-build-deploy` chart into its own separate chart in `https://uselagoon.github.io/lagoon-charts/` so that it can be installed as a sub chart in `lagoon-remote` but also individually installed into OpenShift clusters
* Create `https://amazeeio.github.io/charts/` and move `dbaas-operator` and `dioscuri` and any other non-lagoon specific project charts there (principio?). Then `lagoon-remote` could use them as sub charts

**Comment by tobybellwood** [comment]
yes agree - dbaas-operator and dioscuri are amazee.io operators that Lagoon uses.  build-deploy should be a chart as part of Lagoon.

**Comment by smlx** [comment]
> Move the lagoon-build-deploy chart into its own separate chart in https://uselagoon.github.io/lagoon-charts/ so that it can be installed as a sub chart in lagoon-remote but also individually installed into OpenShift clusters

Thanks for this point. I didn't realise that there was a use-case for `lagoon-build-deploy` outside of `lagoon-remote.

**Comment by tobybellwood** [comment]
> Thanks for this point. I didn't realise that there was a use-case for `lagoon-build-deploy` outside of `lagoon-remote`.

It's very niche/one-time (for now) - basically to install the controllers into existing openshift3 clusters, which can't use the `lagoon-remote` helm chart

**Comment by Schnitzel** [comment]
I also like the suggestion of @shreddedbacon 

```
- Move the lagoon-build-deploy chart into its own separate chart in https://uselagoon.github.io/lagoon-charts/ so that it can be installed as a sub chart in lagoon-remote but also individually installed into OpenShift clusters
- Create https://amazeeio.github.io/charts/ and move dbaas-operator and dioscuri and any other non-lagoon specific project charts there (principio?). Then lagoon-remote could use them as sub charts
```

but for me the charts are part of the code, so I would suggest to to leave the helm charts for `dbaas-operator` inside of https://github.com/amazeeio/dbaas-operator and then we could use: https://charts.amazeeio.github.io/dbaas-operator/ ?
The same also for dioscuri.
