### ISSUE TITLE
Upgrade CRDs to new API

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-charts#299]
According to https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122 the CRD API we use in the `lagoon-build-deploy` chart is no longer going to be available in the next release of kubernetes.

There are some fairly significant changes to the CRD API in `v1` (see link above) that will require changes in the `lagoon-build-deploy` chart templates.

**Comment by shreddedbacon** [comment]
This has already been completed
