### ISSUE TITLE
lagoon-logging fails on eks 1.20

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-charts#313]
trying to install lagoon-logging on an EKS with 1.20 installed fails:

```
  Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.20.7-eks-d88609
```

maybe the check fails because the reported version is prefixed with `v`?

**Comment by smlx** [comment]
Hey @Schnitzel I've added a fix for this so the chart will install. However as discussed previously note that the version of the chart with that constraint only supports `containerd` as the runtime, not `docker`. AFAIK `containerd` is only going to be the default runtime in EKS from `1.22`, but you can select it manually.
