### ISSUE TITLE
Implement cdn ingestion

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-charts#324]
- create fluentd config to ingest syslog from cdn 
- creates new public loadbalancer
- protect via mutual TLS
- sends data to logs-concentrator with clustername `cdn-log-{clustername}-{date}`

**Comment by Schnitzel** [comment]
here a template for the log format:
```
{ "timestamp":%{time.start.sec}V, "service_id":"%{req.service_id}V", "time_elapsed":%{time.elapsed.usec}V, "is_edge":%{if(fastly.ff.visits_this_service == 0, "true", "false")}V, "client_ip":"%{req.http.Fastly-Client-IP}V", "client_as":"%{if(client.as.number!=0, client.as.number, "null")}V", "geo_city":"%{client.geo.city}V", "geo_country_code":"%{client.geo.country_code}V", "request":"%{req.request}V", "host":"%{json.escape(req.http.Host)}V", "url":"%{json.escape(req.url)}V", "request_referer":"%{json.escape(req.http.Referer)}V", "request_user_agent":"%{json.escape(req.http.User-Agent)}V", "resp_status":"%s", "resp_message":"%{resp.response}V", "resp_body_size":%{resp.body_bytes_written}V, "server_datacenter":"%{server.datacenter}V", "cache_status":"%{fastly_info.state}V", "waf_block":"%{req.http.X-Waf-Block}V", "waf_block_id":"%{req.http.X-Waf-Block-Id}V" }```


```
{
  "timestamp": 1629796513,
  "service_id": "3gJgt7cCjLSChTiOevKdkd",
  "time_elapsed": 1064614,
  "is_edge": true,
  "client_ip": "107.170.227.23",
  "client_as": "14061",
  "geo_city": "san francisco",
  "geo_country_code": "US",
  "request": "GET",
  "host": "www.xx.co.nz",
  "url": "/",
  "request_referer": "http://www.xxx.co.nz/",
  "request_user_agent": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/98 Safari/537.4 (StatusCake)",
  "resp_status": "200",
  "resp_message": "OK",
  "resp_body_size": 16362,
  "server_datacenter": "PAO",
  "cache_status": "MISS-CLUSTER",
  "waf_block": "0",
  "waf_block_id": "0"
}```

`is_edge` is the indicator if this request is a first hit (`is_edge: true`) or a shield request (`is_edge:false`).
Let's make it configurable if we want the `is_edge: false` to be sent to the logging infrastructure.

**Comment by smlx** [comment]
> here a template for the log format:

Great! looks good.

> is_edge is the indicator if this request is a first hit (is_edge: true) or a shield request (is_edge:false).
Let's make it configurable if we want the is_edge: false to be sent to the logging infrastructure.

Ah, so is this because we can get multiple logs entries for a single request as it bounces around between PoPs?
