### ISSUE TITLE
Add configurable serviceAnnotation to services

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon-charts#367]
We've identified that certain loadbalancers have annotations that need to be passed (e.g. session connection timeouts for ssh)

We will add a configurable serviceAnnotation (similar to podAnnotation) that allows a chart user to pass the key and value into the annotation.

**Comment by smlx** [comment]
Sounds good, but maybe it would be better placed under `<component>.service.annotations` to mirror `<component>.ingress.annotations`?
