### ISSUE TITLE
Support for proxies

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon-charts#385]
In some cases, a remote could be behind a proxy, it would be handy to be able to pass in the following variables to deployments that need to use a proxy

* HTTP_PROXY / http_proxy
* HTTPS_PROXY / https_proxy
* NO_PROXY

Some services that need to use proxy will be:
* docker-host (https://github.com/uselagoon/lagoon/issues/3036)
* remote-controller (https://github.com/uselagoon/remote-controller/issues/105)

**Comment by smlx** [comment]
We do have additional env vars which can be added in an ad-hoc manner to individual services but I guess you mean having a single variable for all affected services?

**Comment by shreddedbacon** [comment]
> 

Yeah, single var for all affected services would be ideal.

Otherwise extending the ability to providea adhoc envvars to deployment templates would be good. Currently in the lagoon-remote chart, the docker-host deployment doesn't support this (https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-remote/templates/docker-host.deployment.yaml#L29-L71) there may be others, but this is the first one I looked at as it is a requirement for a specific client right now

**Comment by shreddedbacon** [comment]
Some proxy support is already added to remote-controller and docker-host charts
