### ISSUE TITLE
add support for `sigsci-ingress-nginx` router logs

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-charts#414]
at amazee.io we are running an ingress-ngnix with signalscience agent under `sigsci-ingress-nginx`
can we add support for that one?

maybe we just change the regex from `^ingress-nginx$` to `ingress-nginx$` to match any ingress-nginx that might follow?

**Comment by smlx** [comment]
> maybe we just change the regex from `^ingress-nginx$` to `ingress-nginx$` to match any ingress-nginx that might follow?

Logs are classified as router logs based on the following rules in order:

1. check for a label `app.kubernetes.io/name=ingress-nginx`.
2. check for a namespace like `ingress-nginx`.

It is intentionally quite strict to avoid accidentally classifying random stuff as router logs.

In #415 I've just added `sigsci-ingress-nginx` to the list of valid namespaces. If we see demand for a wide range of namespaces in future we can maybe tweak the regex or just rely on the label only.
