### ISSUE TITLE
build logs potentially missing in lagoon-remote release 0.67.0

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon-charts#512]
There was a component in the latest lagoon-remote release 0.67.0 that requires Lagoon-core 2.11.

This can be fixed by rolling lagoon-remote back to 0.66.0

We have marked 0.67.0 as a pre-release in GitHub for now. There are no helm steps that can be taken to hold this release back.

**Comment by smlx** [comment]
What was the actual issue here?

> There are no helm steps that can be taken to hold this release back.

Could you revert the component in the chart and push a new chart version?

**Comment by shreddedbacon** [comment]
I think we can close this now, it is quite old and we've released numerous versions since here
